/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  EventFragment,
  FunctionFragment,
  Result,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  OnEvent,
  PromiseOrValue,
  TypedEvent,
  TypedEventFilter,
  TypedListener,
} from "./common";

export declare namespace LyraAdapter {
  export type OptionPositionStruct = {
    positionId: PromiseOrValue<BigNumberish>;
    strikeId: PromiseOrValue<BigNumberish>;
    optionType: PromiseOrValue<BigNumberish>;
    amount: PromiseOrValue<BigNumberish>;
    collateral: PromiseOrValue<BigNumberish>;
    state: PromiseOrValue<BigNumberish>;
  };

  export type OptionPositionStructOutput = [
    BigNumber,
    BigNumber,
    number,
    BigNumber,
    BigNumber,
    number
  ] & {
    positionId: BigNumber;
    strikeId: BigNumber;
    optionType: number;
    amount: BigNumber;
    collateral: BigNumber;
    state: number;
  };

  export type StrikeStruct = {
    id: PromiseOrValue<BigNumberish>;
    expiry: PromiseOrValue<BigNumberish>;
    strikePrice: PromiseOrValue<BigNumberish>;
    skew: PromiseOrValue<BigNumberish>;
    boardIv: PromiseOrValue<BigNumberish>;
  };

  export type StrikeStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    id: BigNumber;
    expiry: BigNumber;
    strikePrice: BigNumber;
    skew: BigNumber;
    boardIv: BigNumber;
  };
}

export declare namespace DeltaShortStrategy {
  export type DeltaShortStrategyDetailStruct = {
    minTimeToExpiry: PromiseOrValue<BigNumberish>;
    maxTimeToExpiry: PromiseOrValue<BigNumberish>;
    targetDelta: PromiseOrValue<BigNumberish>;
    maxDeltaGap: PromiseOrValue<BigNumberish>;
    minVol: PromiseOrValue<BigNumberish>;
    maxVol: PromiseOrValue<BigNumberish>;
    minTradeInterval: PromiseOrValue<BigNumberish>;
    maxVolVariance: PromiseOrValue<BigNumberish>;
    gwavPeriod: PromiseOrValue<BigNumberish>;
    collatBuffer: PromiseOrValue<BigNumberish>;
    collatPercent: PromiseOrValue<BigNumberish>;
  };

  export type DeltaShortStrategyDetailStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    minTimeToExpiry: BigNumber;
    maxTimeToExpiry: BigNumber;
    targetDelta: BigNumber;
    maxDeltaGap: BigNumber;
    minVol: BigNumber;
    maxVol: BigNumber;
    minTradeInterval: BigNumber;
    maxVolVariance: BigNumber;
    gwavPeriod: BigNumber;
    collatBuffer: BigNumber;
    collatPercent: BigNumber;
  };
}

export interface DeltaShortStrategyInterface extends utils.Interface {
  functions: {
    "_isValidExpiry(uint256)": FunctionFragment;
    "activeStrikeIds(uint256)": FunctionFragment;
    "addAdmin(address)": FunctionFragment;
    "baseAsset()": FunctionFragment;
    "collateralAsset()": FunctionFragment;
    "curveSwap()": FunctionFragment;
    "doTrade(uint256,uint256,address)": FunctionFragment;
    "emergencyCloseAll(address)": FunctionFragment;
    "feeCounter()": FunctionFragment;
    "getAllowedCloseAmount((uint256,uint256,uint8,uint256,uint256,uint8),uint256,uint256)": FunctionFragment;
    "getDeltas(uint256[])": FunctionFragment;
    "getRequiredCollateral((uint256,uint256,uint256,uint256,uint256),uint256)": FunctionFragment;
    "greekCache()": FunctionFragment;
    "gwavOracle()": FunctionFragment;
    "hasOpenPosition()": FunctionFragment;
    "initAdapter(address,address,address,address)": FunctionFragment;
    "isAdmin(address)": FunctionFragment;
    "isValidStrike((uint256,uint256,uint256,uint256,uint256))": FunctionFragment;
    "lastTradeTimestamp(uint256)": FunctionFragment;
    "liquidityPool()": FunctionFragment;
    "lyraRegistry()": FunctionFragment;
    "optionMarket()": FunctionFragment;
    "optionPricer()": FunctionFragment;
    "optionToken()": FunctionFragment;
    "optionType()": FunctionFragment;
    "owner()": FunctionFragment;
    "quoteAsset()": FunctionFragment;
    "reducePosition(uint256,uint256,address)": FunctionFragment;
    "removeAdmin(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "returnFundsAndClearStrikes()": FunctionFragment;
    "roundEnds()": FunctionFragment;
    "setBoard(uint256)": FunctionFragment;
    "setLyraAddresses(address,address,address,address)": FunctionFragment;
    "setStrategyDetail((uint256,uint256,int256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256))": FunctionFragment;
    "shortCollateral()": FunctionFragment;
    "strategyDetail()": FunctionFragment;
    "strikeToPositionId(uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateDelegateApproval()": FunctionFragment;
    "vault()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "_isValidExpiry"
      | "activeStrikeIds"
      | "addAdmin"
      | "baseAsset"
      | "collateralAsset"
      | "curveSwap"
      | "doTrade"
      | "emergencyCloseAll"
      | "feeCounter"
      | "getAllowedCloseAmount"
      | "getDeltas"
      | "getRequiredCollateral"
      | "greekCache"
      | "gwavOracle"
      | "hasOpenPosition"
      | "initAdapter"
      | "isAdmin"
      | "isValidStrike"
      | "lastTradeTimestamp"
      | "liquidityPool"
      | "lyraRegistry"
      | "optionMarket"
      | "optionPricer"
      | "optionToken"
      | "optionType"
      | "owner"
      | "quoteAsset"
      | "reducePosition"
      | "removeAdmin"
      | "renounceOwnership"
      | "returnFundsAndClearStrikes"
      | "roundEnds"
      | "setBoard"
      | "setLyraAddresses"
      | "setStrategyDetail"
      | "shortCollateral"
      | "strategyDetail"
      | "strikeToPositionId"
      | "transferOwnership"
      | "updateDelegateApproval"
      | "vault"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_isValidExpiry",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "activeStrikeIds",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "baseAsset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "collateralAsset",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "curveSwap", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "doTrade",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyCloseAll",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "feeCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllowedCloseAmount",
    values: [
      LyraAdapter.OptionPositionStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeltas",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequiredCollateral",
    values: [LyraAdapter.StrikeStruct, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "greekCache",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gwavOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasOpenPosition",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initAdapter",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidStrike",
    values: [LyraAdapter.StrikeStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "lastTradeTimestamp",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidityPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lyraRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "optionMarket",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "optionPricer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "optionToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "optionType",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quoteAsset",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reducePosition",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "returnFundsAndClearStrikes",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "roundEnds", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setBoard",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setLyraAddresses",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setStrategyDetail",
    values: [DeltaShortStrategy.DeltaShortStrategyDetailStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "shortCollateral",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "strategyDetail",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "strikeToPositionId",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDelegateApproval",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "_isValidExpiry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeStrikeIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baseAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collateralAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "curveSwap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "doTrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyCloseAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeCounter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllowedCloseAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDeltas", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRequiredCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "greekCache", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gwavOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasOpenPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isValidStrike",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastTradeTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidityPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lyraRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "optionMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "optionPricer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "optionToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "optionType", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "quoteAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reducePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "returnFundsAndClearStrikes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "roundEnds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBoard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setLyraAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStrategyDetail",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shortCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "strategyDetail",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "strikeToPositionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDelegateApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;

  events: {
    "AdminAdded(address)": EventFragment;
    "AdminRemoved(address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AdminRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface AdminAddedEventObject {
  newAdmin: string;
}
export type AdminAddedEvent = TypedEvent<[string], AdminAddedEventObject>;

export type AdminAddedEventFilter = TypedEventFilter<AdminAddedEvent>;

export interface AdminRemovedEventObject {
  oldAdmin: string;
}
export type AdminRemovedEvent = TypedEvent<[string], AdminRemovedEventObject>;

export type AdminRemovedEventFilter = TypedEventFilter<AdminRemovedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface DeltaShortStrategy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DeltaShortStrategyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _isValidExpiry(
      expiry: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean] & { isValid: boolean }>;

    activeStrikeIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    addAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    baseAsset(overrides?: CallOverrides): Promise<[string]>;

    collateralAsset(overrides?: CallOverrides): Promise<[string]>;

    curveSwap(overrides?: CallOverrides): Promise<[string]>;

    doTrade(
      strikeId: PromiseOrValue<BigNumberish>,
      sellAmount: PromiseOrValue<BigNumberish>,
      lyraRewardRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    emergencyCloseAll(
      lyraRewardRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    feeCounter(overrides?: CallOverrides): Promise<[string]>;

    getAllowedCloseAmount(
      position: LyraAdapter.OptionPositionStruct,
      strikePrice: PromiseOrValue<BigNumberish>,
      strikeExpiry: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { closeAmount: BigNumber }>;

    getDeltas(
      strikeIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { callDeltas: BigNumber[] }>;

    getRequiredCollateral(
      strike: LyraAdapter.StrikeStruct,
      sellAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        collateralToAdd: BigNumber;
        setCollateralTo: BigNumber;
      }
    >;

    greekCache(overrides?: CallOverrides): Promise<[string]>;

    gwavOracle(overrides?: CallOverrides): Promise<[string]>;

    hasOpenPosition(overrides?: CallOverrides): Promise<[boolean]>;

    initAdapter(
      _lyraRegistry: PromiseOrValue<string>,
      _optionMarket: PromiseOrValue<string>,
      _curveSwap: PromiseOrValue<string>,
      _feeCounter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isAdmin(
      _Admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isValidStrike(
      strike: LyraAdapter.StrikeStruct,
      overrides?: CallOverrides
    ): Promise<[boolean] & { isValid: boolean }>;

    lastTradeTimestamp(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    liquidityPool(overrides?: CallOverrides): Promise<[string]>;

    lyraRegistry(overrides?: CallOverrides): Promise<[string]>;

    optionMarket(overrides?: CallOverrides): Promise<[string]>;

    optionPricer(overrides?: CallOverrides): Promise<[string]>;

    optionToken(overrides?: CallOverrides): Promise<[string]>;

    optionType(overrides?: CallOverrides): Promise<[number]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    quoteAsset(overrides?: CallOverrides): Promise<[string]>;

    reducePosition(
      positionId: PromiseOrValue<BigNumberish>,
      closeAmount: PromiseOrValue<BigNumberish>,
      lyraRewardRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeAdmin(
      oldAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    returnFundsAndClearStrikes(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    roundEnds(overrides?: CallOverrides): Promise<[BigNumber]>;

    setBoard(
      boardId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLyraAddresses(
      _lyraRegistry: PromiseOrValue<string>,
      _optionMarket: PromiseOrValue<string>,
      _curveSwap: PromiseOrValue<string>,
      _feeCounter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setStrategyDetail(
      _deltaStrategy: DeltaShortStrategy.DeltaShortStrategyDetailStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    shortCollateral(overrides?: CallOverrides): Promise<[string]>;

    strategyDetail(overrides?: CallOverrides): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        minTimeToExpiry: BigNumber;
        maxTimeToExpiry: BigNumber;
        targetDelta: BigNumber;
        maxDeltaGap: BigNumber;
        minVol: BigNumber;
        maxVol: BigNumber;
        minTradeInterval: BigNumber;
        maxVolVariance: BigNumber;
        gwavPeriod: BigNumber;
        collatBuffer: BigNumber;
        collatPercent: BigNumber;
      }
    >;

    strikeToPositionId(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateDelegateApproval(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    vault(overrides?: CallOverrides): Promise<[string]>;
  };

  _isValidExpiry(
    expiry: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  activeStrikeIds(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  addAdmin(
    newAdmin: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  baseAsset(overrides?: CallOverrides): Promise<string>;

  collateralAsset(overrides?: CallOverrides): Promise<string>;

  curveSwap(overrides?: CallOverrides): Promise<string>;

  doTrade(
    strikeId: PromiseOrValue<BigNumberish>,
    sellAmount: PromiseOrValue<BigNumberish>,
    lyraRewardRecipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  emergencyCloseAll(
    lyraRewardRecipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  feeCounter(overrides?: CallOverrides): Promise<string>;

  getAllowedCloseAmount(
    position: LyraAdapter.OptionPositionStruct,
    strikePrice: PromiseOrValue<BigNumberish>,
    strikeExpiry: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getDeltas(
    strikeIds: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getRequiredCollateral(
    strike: LyraAdapter.StrikeStruct,
    sellAmount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      collateralToAdd: BigNumber;
      setCollateralTo: BigNumber;
    }
  >;

  greekCache(overrides?: CallOverrides): Promise<string>;

  gwavOracle(overrides?: CallOverrides): Promise<string>;

  hasOpenPosition(overrides?: CallOverrides): Promise<boolean>;

  initAdapter(
    _lyraRegistry: PromiseOrValue<string>,
    _optionMarket: PromiseOrValue<string>,
    _curveSwap: PromiseOrValue<string>,
    _feeCounter: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isAdmin(
    _Admin: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isValidStrike(
    strike: LyraAdapter.StrikeStruct,
    overrides?: CallOverrides
  ): Promise<boolean>;

  lastTradeTimestamp(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  liquidityPool(overrides?: CallOverrides): Promise<string>;

  lyraRegistry(overrides?: CallOverrides): Promise<string>;

  optionMarket(overrides?: CallOverrides): Promise<string>;

  optionPricer(overrides?: CallOverrides): Promise<string>;

  optionToken(overrides?: CallOverrides): Promise<string>;

  optionType(overrides?: CallOverrides): Promise<number>;

  owner(overrides?: CallOverrides): Promise<string>;

  quoteAsset(overrides?: CallOverrides): Promise<string>;

  reducePosition(
    positionId: PromiseOrValue<BigNumberish>,
    closeAmount: PromiseOrValue<BigNumberish>,
    lyraRewardRecipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeAdmin(
    oldAdmin: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  returnFundsAndClearStrikes(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  roundEnds(overrides?: CallOverrides): Promise<BigNumber>;

  setBoard(
    boardId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLyraAddresses(
    _lyraRegistry: PromiseOrValue<string>,
    _optionMarket: PromiseOrValue<string>,
    _curveSwap: PromiseOrValue<string>,
    _feeCounter: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setStrategyDetail(
    _deltaStrategy: DeltaShortStrategy.DeltaShortStrategyDetailStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  shortCollateral(overrides?: CallOverrides): Promise<string>;

  strategyDetail(overrides?: CallOverrides): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      minTimeToExpiry: BigNumber;
      maxTimeToExpiry: BigNumber;
      targetDelta: BigNumber;
      maxDeltaGap: BigNumber;
      minVol: BigNumber;
      maxVol: BigNumber;
      minTradeInterval: BigNumber;
      maxVolVariance: BigNumber;
      gwavPeriod: BigNumber;
      collatBuffer: BigNumber;
      collatPercent: BigNumber;
    }
  >;

  strikeToPositionId(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateDelegateApproval(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  vault(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    _isValidExpiry(
      expiry: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    activeStrikeIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    baseAsset(overrides?: CallOverrides): Promise<string>;

    collateralAsset(overrides?: CallOverrides): Promise<string>;

    curveSwap(overrides?: CallOverrides): Promise<string>;

    doTrade(
      strikeId: PromiseOrValue<BigNumberish>,
      sellAmount: PromiseOrValue<BigNumberish>,
      lyraRewardRecipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        positionId: BigNumber;
        premiumReceived: BigNumber;
        collateralToAdd: BigNumber;
      }
    >;

    emergencyCloseAll(
      lyraRewardRecipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    feeCounter(overrides?: CallOverrides): Promise<string>;

    getAllowedCloseAmount(
      position: LyraAdapter.OptionPositionStruct,
      strikePrice: PromiseOrValue<BigNumberish>,
      strikeExpiry: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDeltas(
      strikeIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getRequiredCollateral(
      strike: LyraAdapter.StrikeStruct,
      sellAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        collateralToAdd: BigNumber;
        setCollateralTo: BigNumber;
      }
    >;

    greekCache(overrides?: CallOverrides): Promise<string>;

    gwavOracle(overrides?: CallOverrides): Promise<string>;

    hasOpenPosition(overrides?: CallOverrides): Promise<boolean>;

    initAdapter(
      _lyraRegistry: PromiseOrValue<string>,
      _optionMarket: PromiseOrValue<string>,
      _curveSwap: PromiseOrValue<string>,
      _feeCounter: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    isAdmin(
      _Admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isValidStrike(
      strike: LyraAdapter.StrikeStruct,
      overrides?: CallOverrides
    ): Promise<boolean>;

    lastTradeTimestamp(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidityPool(overrides?: CallOverrides): Promise<string>;

    lyraRegistry(overrides?: CallOverrides): Promise<string>;

    optionMarket(overrides?: CallOverrides): Promise<string>;

    optionPricer(overrides?: CallOverrides): Promise<string>;

    optionToken(overrides?: CallOverrides): Promise<string>;

    optionType(overrides?: CallOverrides): Promise<number>;

    owner(overrides?: CallOverrides): Promise<string>;

    quoteAsset(overrides?: CallOverrides): Promise<string>;

    reducePosition(
      positionId: PromiseOrValue<BigNumberish>,
      closeAmount: PromiseOrValue<BigNumberish>,
      lyraRewardRecipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeAdmin(
      oldAdmin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    returnFundsAndClearStrikes(overrides?: CallOverrides): Promise<void>;

    roundEnds(overrides?: CallOverrides): Promise<BigNumber>;

    setBoard(
      boardId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setLyraAddresses(
      _lyraRegistry: PromiseOrValue<string>,
      _optionMarket: PromiseOrValue<string>,
      _curveSwap: PromiseOrValue<string>,
      _feeCounter: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setStrategyDetail(
      _deltaStrategy: DeltaShortStrategy.DeltaShortStrategyDetailStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    shortCollateral(overrides?: CallOverrides): Promise<string>;

    strategyDetail(overrides?: CallOverrides): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        minTimeToExpiry: BigNumber;
        maxTimeToExpiry: BigNumber;
        targetDelta: BigNumber;
        maxDeltaGap: BigNumber;
        minVol: BigNumber;
        maxVol: BigNumber;
        minTradeInterval: BigNumber;
        maxVolVariance: BigNumber;
        gwavPeriod: BigNumber;
        collatBuffer: BigNumber;
        collatPercent: BigNumber;
      }
    >;

    strikeToPositionId(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateDelegateApproval(overrides?: CallOverrides): Promise<void>;

    vault(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "AdminAdded(address)"(
      newAdmin?: PromiseOrValue<string> | null
    ): AdminAddedEventFilter;
    AdminAdded(newAdmin?: PromiseOrValue<string> | null): AdminAddedEventFilter;

    "AdminRemoved(address)"(
      oldAdmin?: PromiseOrValue<string> | null
    ): AdminRemovedEventFilter;
    AdminRemoved(
      oldAdmin?: PromiseOrValue<string> | null
    ): AdminRemovedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    _isValidExpiry(
      expiry: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    activeStrikeIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    baseAsset(overrides?: CallOverrides): Promise<BigNumber>;

    collateralAsset(overrides?: CallOverrides): Promise<BigNumber>;

    curveSwap(overrides?: CallOverrides): Promise<BigNumber>;

    doTrade(
      strikeId: PromiseOrValue<BigNumberish>,
      sellAmount: PromiseOrValue<BigNumberish>,
      lyraRewardRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    emergencyCloseAll(
      lyraRewardRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    feeCounter(overrides?: CallOverrides): Promise<BigNumber>;

    getAllowedCloseAmount(
      position: LyraAdapter.OptionPositionStruct,
      strikePrice: PromiseOrValue<BigNumberish>,
      strikeExpiry: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDeltas(
      strikeIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRequiredCollateral(
      strike: LyraAdapter.StrikeStruct,
      sellAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    greekCache(overrides?: CallOverrides): Promise<BigNumber>;

    gwavOracle(overrides?: CallOverrides): Promise<BigNumber>;

    hasOpenPosition(overrides?: CallOverrides): Promise<BigNumber>;

    initAdapter(
      _lyraRegistry: PromiseOrValue<string>,
      _optionMarket: PromiseOrValue<string>,
      _curveSwap: PromiseOrValue<string>,
      _feeCounter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isAdmin(
      _Admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidStrike(
      strike: LyraAdapter.StrikeStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastTradeTimestamp(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidityPool(overrides?: CallOverrides): Promise<BigNumber>;

    lyraRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    optionMarket(overrides?: CallOverrides): Promise<BigNumber>;

    optionPricer(overrides?: CallOverrides): Promise<BigNumber>;

    optionToken(overrides?: CallOverrides): Promise<BigNumber>;

    optionType(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    quoteAsset(overrides?: CallOverrides): Promise<BigNumber>;

    reducePosition(
      positionId: PromiseOrValue<BigNumberish>,
      closeAmount: PromiseOrValue<BigNumberish>,
      lyraRewardRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeAdmin(
      oldAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    returnFundsAndClearStrikes(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    roundEnds(overrides?: CallOverrides): Promise<BigNumber>;

    setBoard(
      boardId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLyraAddresses(
      _lyraRegistry: PromiseOrValue<string>,
      _optionMarket: PromiseOrValue<string>,
      _curveSwap: PromiseOrValue<string>,
      _feeCounter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setStrategyDetail(
      _deltaStrategy: DeltaShortStrategy.DeltaShortStrategyDetailStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    shortCollateral(overrides?: CallOverrides): Promise<BigNumber>;

    strategyDetail(overrides?: CallOverrides): Promise<BigNumber>;

    strikeToPositionId(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateDelegateApproval(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    vault(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    _isValidExpiry(
      expiry: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    activeStrikeIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    baseAsset(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    collateralAsset(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    curveSwap(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    doTrade(
      strikeId: PromiseOrValue<BigNumberish>,
      sellAmount: PromiseOrValue<BigNumberish>,
      lyraRewardRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    emergencyCloseAll(
      lyraRewardRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    feeCounter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAllowedCloseAmount(
      position: LyraAdapter.OptionPositionStruct,
      strikePrice: PromiseOrValue<BigNumberish>,
      strikeExpiry: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDeltas(
      strikeIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRequiredCollateral(
      strike: LyraAdapter.StrikeStruct,
      sellAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    greekCache(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gwavOracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hasOpenPosition(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initAdapter(
      _lyraRegistry: PromiseOrValue<string>,
      _optionMarket: PromiseOrValue<string>,
      _curveSwap: PromiseOrValue<string>,
      _feeCounter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isAdmin(
      _Admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidStrike(
      strike: LyraAdapter.StrikeStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lastTradeTimestamp(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    liquidityPool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lyraRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    optionMarket(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    optionPricer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    optionToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    optionType(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    quoteAsset(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    reducePosition(
      positionId: PromiseOrValue<BigNumberish>,
      closeAmount: PromiseOrValue<BigNumberish>,
      lyraRewardRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeAdmin(
      oldAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    returnFundsAndClearStrikes(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    roundEnds(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setBoard(
      boardId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLyraAddresses(
      _lyraRegistry: PromiseOrValue<string>,
      _optionMarket: PromiseOrValue<string>,
      _curveSwap: PromiseOrValue<string>,
      _feeCounter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setStrategyDetail(
      _deltaStrategy: DeltaShortStrategy.DeltaShortStrategyDetailStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    shortCollateral(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    strategyDetail(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    strikeToPositionId(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateDelegateApproval(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    vault(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
