/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  EventFragment,
  FunctionFragment,
  Result,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  OnEvent,
  PromiseOrValue,
  TypedEvent,
  TypedEventFilter,
  TypedListener,
} from "./common";

export declare namespace LongGammaStrategy {
  export type LongGammaStrategyDetailStruct = {
    minTimeToExpiry: PromiseOrValue<BigNumberish>;
    maxTimeToExpiry: PromiseOrValue<BigNumberish>;
    targetStraddleDelta: PromiseOrValue<BigNumberish>;
    maxDeltaGap: PromiseOrValue<BigNumberish>;
    maxVol: PromiseOrValue<BigNumberish>;
    minTradeInterval: PromiseOrValue<BigNumberish>;
    minDeltaToHedge: PromiseOrValue<BigNumberish>;
    maxUnhedgedInterval: PromiseOrValue<BigNumberish>;
    maxTradeUtilization: PromiseOrValue<BigNumberish>;
    timeBetweenRoundEndAndExpiry: PromiseOrValue<BigNumberish>;
  };

  export type LongGammaStrategyDetailStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    minTimeToExpiry: BigNumber;
    maxTimeToExpiry: BigNumber;
    targetStraddleDelta: BigNumber;
    maxDeltaGap: BigNumber;
    maxVol: BigNumber;
    minTradeInterval: BigNumber;
    minDeltaToHedge: BigNumber;
    maxUnhedgedInterval: BigNumber;
    maxTradeUtilization: BigNumber;
    timeBetweenRoundEndAndExpiry: BigNumber;
  };
}

export interface LongGammaStrategyInterface extends utils.Interface {
  functions: {
    "_isValidExpiry(uint256)": FunctionFragment;
    "addAdmin(address)": FunctionFragment;
    "board()": FunctionFragment;
    "deltaHedge(uint256)": FunctionFragment;
    "doTrade(uint256)": FunctionFragment;
    "emergencyCloseAll()": FunctionFragment;
    "hasOpenPosition()": FunctionFragment;
    "isAdmin(address)": FunctionFragment;
    "isValidStrike(uint256)": FunctionFragment;
    "oneClicks()": FunctionFragment;
    "reducePosition(uint256)": FunctionFragment;
    "removeAdmin(address)": FunctionFragment;
    "returnFundsToVault()": FunctionFragment;
    "setBoard(uint256)": FunctionFragment;
    "setOneClicks(address)": FunctionFragment;
    "setStrategyDetail((uint256,uint256,int256,uint256,uint256,uint256,uint256,uint256,uint256,uint256))": FunctionFragment;
    "shouldWeHedge()": FunctionFragment;
    "strategyDetail()": FunctionFragment;
    "underlier()": FunctionFragment;
    "vault()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "_isValidExpiry"
      | "addAdmin"
      | "board"
      | "deltaHedge"
      | "doTrade"
      | "emergencyCloseAll"
      | "hasOpenPosition"
      | "isAdmin"
      | "isValidStrike"
      | "oneClicks"
      | "reducePosition"
      | "removeAdmin"
      | "returnFundsToVault"
      | "setBoard"
      | "setOneClicks"
      | "setStrategyDetail"
      | "shouldWeHedge"
      | "strategyDetail"
      | "underlier"
      | "vault"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_isValidExpiry",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "board", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deltaHedge",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "doTrade",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyCloseAll",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasOpenPosition",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidStrike",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "oneClicks", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reducePosition",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "returnFundsToVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBoard",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setOneClicks",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setStrategyDetail",
    values: [LongGammaStrategy.LongGammaStrategyDetailStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "shouldWeHedge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "strategyDetail",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "underlier", values?: undefined): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "_isValidExpiry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "board", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deltaHedge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "doTrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyCloseAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasOpenPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isValidStrike",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oneClicks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reducePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "returnFundsToVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBoard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setOneClicks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStrategyDetail",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shouldWeHedge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "strategyDetail",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "underlier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;

  events: {
    "AdminAdded(address)": EventFragment;
    "AdminRemoved(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AdminRemoved"): EventFragment;
}

export interface AdminAddedEventObject {
  newAdmin: string;
}
export type AdminAddedEvent = TypedEvent<[string], AdminAddedEventObject>;

export type AdminAddedEventFilter = TypedEventFilter<AdminAddedEvent>;

export interface AdminRemovedEventObject {
  oldAdmin: string;
}
export type AdminRemovedEvent = TypedEvent<[string], AdminRemovedEventObject>;

export type AdminRemovedEventFilter = TypedEventFilter<AdminRemovedEvent>;

export interface LongGammaStrategy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LongGammaStrategyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _isValidExpiry(
      expiry: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean] & { isValid: boolean }>;

    addAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    board(overrides?: CallOverrides): Promise<
      [BigNumber, BigNumber, BigNumber, boolean] & {
        id: BigNumber;
        expiry: BigNumber;
        iv: BigNumber;
        frozen: boolean;
      }
    >;

    deltaHedge(
      hedgeType: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    doTrade(
      strikeId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    emergencyCloseAll(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    hasOpenPosition(overrides?: CallOverrides): Promise<[boolean]>;

    isAdmin(
      _Admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isValidStrike(
      strikeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean] & { isValid: boolean }>;

    oneClicks(overrides?: CallOverrides): Promise<[string]>;

    reducePosition(
      closeAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeAdmin(
      oldAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    returnFundsToVault(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setBoard(
      _boardId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setOneClicks(
      _oneClicksAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setStrategyDetail(
      _longGammaStrategy: LongGammaStrategy.LongGammaStrategyDetailStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    shouldWeHedge(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    strategyDetail(overrides?: CallOverrides): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        minTimeToExpiry: BigNumber;
        maxTimeToExpiry: BigNumber;
        targetStraddleDelta: BigNumber;
        maxDeltaGap: BigNumber;
        maxVol: BigNumber;
        minTradeInterval: BigNumber;
        minDeltaToHedge: BigNumber;
        maxUnhedgedInterval: BigNumber;
        maxTradeUtilization: BigNumber;
        timeBetweenRoundEndAndExpiry: BigNumber;
      }
    >;

    underlier(overrides?: CallOverrides): Promise<[string]>;

    vault(overrides?: CallOverrides): Promise<[string]>;
  };

  _isValidExpiry(
    expiry: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  addAdmin(
    newAdmin: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  board(overrides?: CallOverrides): Promise<
    [BigNumber, BigNumber, BigNumber, boolean] & {
      id: BigNumber;
      expiry: BigNumber;
      iv: BigNumber;
      frozen: boolean;
    }
  >;

  deltaHedge(
    hedgeType: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  doTrade(
    strikeId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  emergencyCloseAll(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  hasOpenPosition(overrides?: CallOverrides): Promise<boolean>;

  isAdmin(
    _Admin: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isValidStrike(
    strikeId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  oneClicks(overrides?: CallOverrides): Promise<string>;

  reducePosition(
    closeAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeAdmin(
    oldAdmin: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  returnFundsToVault(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setBoard(
    _boardId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setOneClicks(
    _oneClicksAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setStrategyDetail(
    _longGammaStrategy: LongGammaStrategy.LongGammaStrategyDetailStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  shouldWeHedge(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber, BigNumber]>;

  strategyDetail(overrides?: CallOverrides): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      minTimeToExpiry: BigNumber;
      maxTimeToExpiry: BigNumber;
      targetStraddleDelta: BigNumber;
      maxDeltaGap: BigNumber;
      maxVol: BigNumber;
      minTradeInterval: BigNumber;
      minDeltaToHedge: BigNumber;
      maxUnhedgedInterval: BigNumber;
      maxTradeUtilization: BigNumber;
      timeBetweenRoundEndAndExpiry: BigNumber;
    }
  >;

  underlier(overrides?: CallOverrides): Promise<string>;

  vault(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    _isValidExpiry(
      expiry: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    addAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    board(overrides?: CallOverrides): Promise<
      [BigNumber, BigNumber, BigNumber, boolean] & {
        id: BigNumber;
        expiry: BigNumber;
        iv: BigNumber;
        frozen: boolean;
      }
    >;

    deltaHedge(
      hedgeType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber[]]>;

    doTrade(
      strikeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber[]] & {
        balChange: BigNumber;
        positionIds: BigNumber[];
      }
    >;

    emergencyCloseAll(overrides?: CallOverrides): Promise<BigNumber>;

    hasOpenPosition(overrides?: CallOverrides): Promise<boolean>;

    isAdmin(
      _Admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isValidStrike(
      strikeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    oneClicks(overrides?: CallOverrides): Promise<string>;

    reducePosition(
      closeAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber[]] & {
        balChange: BigNumber;
        positionIds: BigNumber[];
      }
    >;

    removeAdmin(
      oldAdmin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    returnFundsToVault(overrides?: CallOverrides): Promise<void>;

    setBoard(
      _boardId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setOneClicks(
      _oneClicksAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setStrategyDetail(
      _longGammaStrategy: LongGammaStrategy.LongGammaStrategyDetailStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    shouldWeHedge(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    strategyDetail(overrides?: CallOverrides): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        minTimeToExpiry: BigNumber;
        maxTimeToExpiry: BigNumber;
        targetStraddleDelta: BigNumber;
        maxDeltaGap: BigNumber;
        maxVol: BigNumber;
        minTradeInterval: BigNumber;
        minDeltaToHedge: BigNumber;
        maxUnhedgedInterval: BigNumber;
        maxTradeUtilization: BigNumber;
        timeBetweenRoundEndAndExpiry: BigNumber;
      }
    >;

    underlier(overrides?: CallOverrides): Promise<string>;

    vault(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "AdminAdded(address)"(
      newAdmin?: PromiseOrValue<string> | null
    ): AdminAddedEventFilter;
    AdminAdded(newAdmin?: PromiseOrValue<string> | null): AdminAddedEventFilter;

    "AdminRemoved(address)"(
      oldAdmin?: PromiseOrValue<string> | null
    ): AdminRemovedEventFilter;
    AdminRemoved(
      oldAdmin?: PromiseOrValue<string> | null
    ): AdminRemovedEventFilter;
  };

  estimateGas: {
    _isValidExpiry(
      expiry: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    board(overrides?: CallOverrides): Promise<BigNumber>;

    deltaHedge(
      hedgeType: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    doTrade(
      strikeId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    emergencyCloseAll(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    hasOpenPosition(overrides?: CallOverrides): Promise<BigNumber>;

    isAdmin(
      _Admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidStrike(
      strikeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    oneClicks(overrides?: CallOverrides): Promise<BigNumber>;

    reducePosition(
      closeAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeAdmin(
      oldAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    returnFundsToVault(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setBoard(
      _boardId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setOneClicks(
      _oneClicksAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setStrategyDetail(
      _longGammaStrategy: LongGammaStrategy.LongGammaStrategyDetailStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    shouldWeHedge(overrides?: CallOverrides): Promise<BigNumber>;

    strategyDetail(overrides?: CallOverrides): Promise<BigNumber>;

    underlier(overrides?: CallOverrides): Promise<BigNumber>;

    vault(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    _isValidExpiry(
      expiry: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    board(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deltaHedge(
      hedgeType: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    doTrade(
      strikeId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    emergencyCloseAll(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    hasOpenPosition(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isAdmin(
      _Admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidStrike(
      strikeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    oneClicks(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    reducePosition(
      closeAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeAdmin(
      oldAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    returnFundsToVault(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setBoard(
      _boardId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setOneClicks(
      _oneClicksAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setStrategyDetail(
      _longGammaStrategy: LongGammaStrategy.LongGammaStrategyDetailStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    shouldWeHedge(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    strategyDetail(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    underlier(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    vault(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
