/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  EventFragment,
  FunctionFragment,
  Result,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  OnEvent,
  PromiseOrValue,
  TypedEvent,
  TypedEventFilter,
  TypedListener,
} from "./common";

export declare namespace OneClicks {
  export type PositionsToCloseStruct = {
    underlier: PromiseOrValue<string>;
    positionIds: PromiseOrValue<BigNumberish>[];
  };

  export type PositionsToCloseStructOutput = [string, BigNumber[]] & {
    underlier: string;
    positionIds: BigNumber[];
  };

  export type LegDetailsStruct = {
    amount: PromiseOrValue<BigNumberish>;
    strikeId: PromiseOrValue<BigNumberish>;
    isCall: PromiseOrValue<boolean>;
    isLong: PromiseOrValue<boolean>;
    finalPositionCollateral: PromiseOrValue<BigNumberish>;
  };

  export type LegDetailsStructOutput = [
    BigNumber,
    BigNumber,
    boolean,
    boolean,
    BigNumber
  ] & {
    amount: BigNumber;
    strikeId: BigNumber;
    isCall: boolean;
    isLong: boolean;
    finalPositionCollateral: BigNumber;
  };
}

export interface OneClicksInterface extends utils.Interface {
  functions: {
    "addAdmin(address)": FunctionFragment;
    "addMarket(string,address,address,address,address)": FunctionFragment;
    "addStrategy(string,bool[])": FunctionFragment;
    "closeAllPositions(string[])": FunctionFragment;
    "closeAllPositionsByUnderlier(string)": FunctionFragment;
    "closeFeeBasisPoint()": FunctionFragment;
    "closeSelectedPositions((string,uint256[])[])": FunctionFragment;
    "closeSelectedPositionsByUnderlier(string,uint256[])": FunctionFragment;
    "deleteMarket(string)": FunctionFragment;
    "deleteStrategy(string)": FunctionFragment;
    "emergencyWithdrawal()": FunctionFragment;
    "getDeltas(string,uint256)": FunctionFragment;
    "getExistingPosition(string,uint256,bool)": FunctionFragment;
    "getMinCollateralForStrike(string,bool,bool,uint256,uint256)": FunctionFragment;
    "getOptionPrices(string,uint256)": FunctionFragment;
    "getStrikeIV(string,uint256)": FunctionFragment;
    "isAdmin(address)": FunctionFragment;
    "licenseFeeBasisPoint()": FunctionFragment;
    "licenseFeeCap()": FunctionFragment;
    "licenseFeeRecipient()": FunctionFragment;
    "lyraRewardRecipient()": FunctionFragment;
    "marketToToken(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "quoteAsset()": FunctionFragment;
    "removeAdmin(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setCloseFeeRate(uint256)": FunctionFragment;
    "setLicenseFeeCap(uint256)": FunctionFragment;
    "setLicenseFeeRate(uint256)": FunctionFragment;
    "setLicenseFeeRecipient(address)": FunctionFragment;
    "setLyraRewardRecipient(address)": FunctionFragment;
    "synthetixAdapter()": FunctionFragment;
    "tradeOneClick(string,string,uint256,(uint256,uint256,bool,bool,uint256)[])": FunctionFragment;
    "tradingRewards()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "underlierToMarket(string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addAdmin"
      | "addMarket"
      | "addStrategy"
      | "closeAllPositions"
      | "closeAllPositionsByUnderlier"
      | "closeFeeBasisPoint"
      | "closeSelectedPositions"
      | "closeSelectedPositionsByUnderlier"
      | "deleteMarket"
      | "deleteStrategy"
      | "emergencyWithdrawal"
      | "getDeltas"
      | "getExistingPosition"
      | "getMinCollateralForStrike"
      | "getOptionPrices"
      | "getStrikeIV"
      | "isAdmin"
      | "licenseFeeBasisPoint"
      | "licenseFeeCap"
      | "licenseFeeRecipient"
      | "lyraRewardRecipient"
      | "marketToToken"
      | "owner"
      | "quoteAsset"
      | "removeAdmin"
      | "renounceOwnership"
      | "setCloseFeeRate"
      | "setLicenseFeeCap"
      | "setLicenseFeeRate"
      | "setLicenseFeeRecipient"
      | "setLyraRewardRecipient"
      | "synthetixAdapter"
      | "tradeOneClick"
      | "tradingRewards"
      | "transferOwnership"
      | "underlierToMarket"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addMarket",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addStrategy",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "closeAllPositions",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "closeAllPositionsByUnderlier",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "closeFeeBasisPoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "closeSelectedPositions",
    values: [OneClicks.PositionsToCloseStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "closeSelectedPositionsByUnderlier",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteMarket",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteStrategy",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDeltas",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getExistingPosition",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinCollateralForStrike",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getOptionPrices",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getStrikeIV",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "licenseFeeBasisPoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "licenseFeeCap",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "licenseFeeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lyraRewardRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "marketToToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quoteAsset",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCloseFeeRate",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setLicenseFeeCap",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setLicenseFeeRate",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setLicenseFeeRecipient",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setLyraRewardRecipient",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "synthetixAdapter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tradeOneClick",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      OneClicks.LegDetailsStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "tradingRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "underlierToMarket",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeAllPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeAllPositionsByUnderlier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeFeeBasisPoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeSelectedPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeSelectedPositionsByUnderlier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDeltas", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getExistingPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinCollateralForStrike",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOptionPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStrikeIV",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "licenseFeeBasisPoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "licenseFeeCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "licenseFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lyraRewardRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketToToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "quoteAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCloseFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLicenseFeeCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLicenseFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLicenseFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLyraRewardRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "synthetixAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tradeOneClick",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tradingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "underlierToMarket",
    data: BytesLike
  ): Result;

  events: {
    "AdminAdded(address)": EventFragment;
    "AdminRemoved(address)": EventFragment;
    "OneClicksTraded(string,string,uint256,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "PositionTraded(string,bool,bool,uint256,uint256,uint256,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AdminRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OneClicksTraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PositionTraded"): EventFragment;
}

export interface AdminAddedEventObject {
  newAdmin: string;
}
export type AdminAddedEvent = TypedEvent<[string], AdminAddedEventObject>;

export type AdminAddedEventFilter = TypedEventFilter<AdminAddedEvent>;

export interface AdminRemovedEventObject {
  oldAdmin: string;
}
export type AdminRemovedEvent = TypedEvent<[string], AdminRemovedEventObject>;

export type AdminRemovedEventFilter = TypedEventFilter<AdminRemovedEvent>;

export interface OneClicksTradedEventObject {
  underlier: string;
  oneClickName: string;
  totalAbsCost: BigNumber;
  licenseFee: BigNumber;
}
export type OneClicksTradedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  OneClicksTradedEventObject
>;

export type OneClicksTradedEventFilter = TypedEventFilter<OneClicksTradedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PositionTradedEventObject {
  underlier: string;
  isLong: boolean;
  isClose: boolean;
  positionId: BigNumber;
  amount: BigNumber;
  totalCost: BigNumber;
  totalLyraFee: BigNumber;
  owner: string;
}
export type PositionTradedEvent = TypedEvent<
  [
    string,
    boolean,
    boolean,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string
  ],
  PositionTradedEventObject
>;

export type PositionTradedEventFilter = TypedEventFilter<PositionTradedEvent>;

export interface OneClicks extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OneClicksInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addMarket(
      underlier: PromiseOrValue<string>,
      market: PromiseOrValue<string>,
      token: PromiseOrValue<string>,
      greekCache: PromiseOrValue<string>,
      pricer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addStrategy(
      oneClickName: PromiseOrValue<string>,
      legsIsCall: PromiseOrValue<boolean>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    closeAllPositions(
      underliers: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    closeAllPositionsByUnderlier(
      underlier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    closeFeeBasisPoint(overrides?: CallOverrides): Promise<[BigNumber]>;

    closeSelectedPositions(
      toClose: OneClicks.PositionsToCloseStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    closeSelectedPositionsByUnderlier(
      underlier: PromiseOrValue<string>,
      positionIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deleteMarket(
      underlier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deleteStrategy(
      oneClickName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    emergencyWithdrawal(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getDeltas(
      underlier: PromiseOrValue<string>,
      strikeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getExistingPosition(
      underlier: PromiseOrValue<string>,
      strikeId: PromiseOrValue<BigNumberish>,
      isCall: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean, BigNumber] & {
        positionId: BigNumber;
        positionAmount: BigNumber;
        isLong: boolean;
        collateral: BigNumber;
      }
    >;

    getMinCollateralForStrike(
      underlier: PromiseOrValue<string>,
      isCall: PromiseOrValue<boolean>,
      isLong: PromiseOrValue<boolean>,
      strikeId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getOptionPrices(
      underlier: PromiseOrValue<string>,
      strikeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { callPrice: BigNumber; putPrice: BigNumber }
    >;

    getStrikeIV(
      underlier: PromiseOrValue<string>,
      strikeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { iv: BigNumber }>;

    isAdmin(
      _Admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    licenseFeeBasisPoint(overrides?: CallOverrides): Promise<[BigNumber]>;

    licenseFeeCap(overrides?: CallOverrides): Promise<[BigNumber]>;

    licenseFeeRecipient(overrides?: CallOverrides): Promise<[string]>;

    lyraRewardRecipient(overrides?: CallOverrides): Promise<[string]>;

    marketToToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    quoteAsset(overrides?: CallOverrides): Promise<[string]>;

    removeAdmin(
      oldAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setCloseFeeRate(
      newCFBP: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLicenseFeeCap(
      newLFCap: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLicenseFeeRate(
      newLFBP: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLicenseFeeRecipient(
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLyraRewardRecipient(
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    synthetixAdapter(overrides?: CallOverrides): Promise<[string]>;

    tradeOneClick(
      oneClickName: PromiseOrValue<string>,
      underlier: PromiseOrValue<string>,
      estimatedCost: PromiseOrValue<BigNumberish>,
      inputLegs: OneClicks.LegDetailsStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    tradingRewards(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    underlierToMarket(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  addAdmin(
    newAdmin: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addMarket(
    underlier: PromiseOrValue<string>,
    market: PromiseOrValue<string>,
    token: PromiseOrValue<string>,
    greekCache: PromiseOrValue<string>,
    pricer: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addStrategy(
    oneClickName: PromiseOrValue<string>,
    legsIsCall: PromiseOrValue<boolean>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  closeAllPositions(
    underliers: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  closeAllPositionsByUnderlier(
    underlier: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  closeFeeBasisPoint(overrides?: CallOverrides): Promise<BigNumber>;

  closeSelectedPositions(
    toClose: OneClicks.PositionsToCloseStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  closeSelectedPositionsByUnderlier(
    underlier: PromiseOrValue<string>,
    positionIds: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deleteMarket(
    underlier: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deleteStrategy(
    oneClickName: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  emergencyWithdrawal(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getDeltas(
    underlier: PromiseOrValue<string>,
    strikeId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  getExistingPosition(
    underlier: PromiseOrValue<string>,
    strikeId: PromiseOrValue<BigNumberish>,
    isCall: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, boolean, BigNumber] & {
      positionId: BigNumber;
      positionAmount: BigNumber;
      isLong: boolean;
      collateral: BigNumber;
    }
  >;

  getMinCollateralForStrike(
    underlier: PromiseOrValue<string>,
    isCall: PromiseOrValue<boolean>,
    isLong: PromiseOrValue<boolean>,
    strikeId: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getOptionPrices(
    underlier: PromiseOrValue<string>,
    strikeId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { callPrice: BigNumber; putPrice: BigNumber }
  >;

  getStrikeIV(
    underlier: PromiseOrValue<string>,
    strikeId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  isAdmin(
    _Admin: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  licenseFeeBasisPoint(overrides?: CallOverrides): Promise<BigNumber>;

  licenseFeeCap(overrides?: CallOverrides): Promise<BigNumber>;

  licenseFeeRecipient(overrides?: CallOverrides): Promise<string>;

  lyraRewardRecipient(overrides?: CallOverrides): Promise<string>;

  marketToToken(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  quoteAsset(overrides?: CallOverrides): Promise<string>;

  removeAdmin(
    oldAdmin: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setCloseFeeRate(
    newCFBP: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLicenseFeeCap(
    newLFCap: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLicenseFeeRate(
    newLFBP: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLicenseFeeRecipient(
    recipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLyraRewardRecipient(
    recipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  synthetixAdapter(overrides?: CallOverrides): Promise<string>;

  tradeOneClick(
    oneClickName: PromiseOrValue<string>,
    underlier: PromiseOrValue<string>,
    estimatedCost: PromiseOrValue<BigNumberish>,
    inputLegs: OneClicks.LegDetailsStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  tradingRewards(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  underlierToMarket(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    addAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addMarket(
      underlier: PromiseOrValue<string>,
      market: PromiseOrValue<string>,
      token: PromiseOrValue<string>,
      greekCache: PromiseOrValue<string>,
      pricer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addStrategy(
      oneClickName: PromiseOrValue<string>,
      legsIsCall: PromiseOrValue<boolean>[],
      overrides?: CallOverrides
    ): Promise<void>;

    closeAllPositions(
      underliers: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    closeAllPositionsByUnderlier(
      underlier: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    closeFeeBasisPoint(overrides?: CallOverrides): Promise<BigNumber>;

    closeSelectedPositions(
      toClose: OneClicks.PositionsToCloseStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    closeSelectedPositionsByUnderlier(
      underlier: PromiseOrValue<string>,
      positionIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    deleteMarket(
      underlier: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    deleteStrategy(
      oneClickName: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    emergencyWithdrawal(overrides?: CallOverrides): Promise<void>;

    getDeltas(
      underlier: PromiseOrValue<string>,
      strikeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getExistingPosition(
      underlier: PromiseOrValue<string>,
      strikeId: PromiseOrValue<BigNumberish>,
      isCall: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean, BigNumber] & {
        positionId: BigNumber;
        positionAmount: BigNumber;
        isLong: boolean;
        collateral: BigNumber;
      }
    >;

    getMinCollateralForStrike(
      underlier: PromiseOrValue<string>,
      isCall: PromiseOrValue<boolean>,
      isLong: PromiseOrValue<boolean>,
      strikeId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOptionPrices(
      underlier: PromiseOrValue<string>,
      strikeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { callPrice: BigNumber; putPrice: BigNumber }
    >;

    getStrikeIV(
      underlier: PromiseOrValue<string>,
      strikeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isAdmin(
      _Admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    licenseFeeBasisPoint(overrides?: CallOverrides): Promise<BigNumber>;

    licenseFeeCap(overrides?: CallOverrides): Promise<BigNumber>;

    licenseFeeRecipient(overrides?: CallOverrides): Promise<string>;

    lyraRewardRecipient(overrides?: CallOverrides): Promise<string>;

    marketToToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    quoteAsset(overrides?: CallOverrides): Promise<string>;

    removeAdmin(
      oldAdmin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setCloseFeeRate(
      newCFBP: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setLicenseFeeCap(
      newLFCap: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setLicenseFeeRate(
      newLFBP: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setLicenseFeeRecipient(
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setLyraRewardRecipient(
      recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    synthetixAdapter(overrides?: CallOverrides): Promise<string>;

    tradeOneClick(
      oneClickName: PromiseOrValue<string>,
      underlier: PromiseOrValue<string>,
      estimatedCost: PromiseOrValue<BigNumberish>,
      inputLegs: OneClicks.LegDetailsStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    tradingRewards(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    underlierToMarket(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "AdminAdded(address)"(
      newAdmin?: PromiseOrValue<string> | null
    ): AdminAddedEventFilter;
    AdminAdded(newAdmin?: PromiseOrValue<string> | null): AdminAddedEventFilter;

    "AdminRemoved(address)"(
      oldAdmin?: PromiseOrValue<string> | null
    ): AdminRemovedEventFilter;
    AdminRemoved(
      oldAdmin?: PromiseOrValue<string> | null
    ): AdminRemovedEventFilter;

    "OneClicksTraded(string,string,uint256,uint256)"(
      underlier?: null,
      oneClickName?: null,
      totalAbsCost?: null,
      licenseFee?: null
    ): OneClicksTradedEventFilter;
    OneClicksTraded(
      underlier?: null,
      oneClickName?: null,
      totalAbsCost?: null,
      licenseFee?: null
    ): OneClicksTradedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "PositionTraded(string,bool,bool,uint256,uint256,uint256,uint256,address)"(
      underlier?: null,
      isLong?: null,
      isClose?: null,
      positionId?: PromiseOrValue<BigNumberish> | null,
      amount?: null,
      totalCost?: null,
      totalLyraFee?: null,
      owner?: PromiseOrValue<string> | null
    ): PositionTradedEventFilter;
    PositionTraded(
      underlier?: null,
      isLong?: null,
      isClose?: null,
      positionId?: PromiseOrValue<BigNumberish> | null,
      amount?: null,
      totalCost?: null,
      totalLyraFee?: null,
      owner?: PromiseOrValue<string> | null
    ): PositionTradedEventFilter;
  };

  estimateGas: {
    addAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addMarket(
      underlier: PromiseOrValue<string>,
      market: PromiseOrValue<string>,
      token: PromiseOrValue<string>,
      greekCache: PromiseOrValue<string>,
      pricer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addStrategy(
      oneClickName: PromiseOrValue<string>,
      legsIsCall: PromiseOrValue<boolean>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    closeAllPositions(
      underliers: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    closeAllPositionsByUnderlier(
      underlier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    closeFeeBasisPoint(overrides?: CallOverrides): Promise<BigNumber>;

    closeSelectedPositions(
      toClose: OneClicks.PositionsToCloseStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    closeSelectedPositionsByUnderlier(
      underlier: PromiseOrValue<string>,
      positionIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deleteMarket(
      underlier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deleteStrategy(
      oneClickName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    emergencyWithdrawal(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getDeltas(
      underlier: PromiseOrValue<string>,
      strikeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getExistingPosition(
      underlier: PromiseOrValue<string>,
      strikeId: PromiseOrValue<BigNumberish>,
      isCall: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMinCollateralForStrike(
      underlier: PromiseOrValue<string>,
      isCall: PromiseOrValue<boolean>,
      isLong: PromiseOrValue<boolean>,
      strikeId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOptionPrices(
      underlier: PromiseOrValue<string>,
      strikeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStrikeIV(
      underlier: PromiseOrValue<string>,
      strikeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isAdmin(
      _Admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    licenseFeeBasisPoint(overrides?: CallOverrides): Promise<BigNumber>;

    licenseFeeCap(overrides?: CallOverrides): Promise<BigNumber>;

    licenseFeeRecipient(overrides?: CallOverrides): Promise<BigNumber>;

    lyraRewardRecipient(overrides?: CallOverrides): Promise<BigNumber>;

    marketToToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    quoteAsset(overrides?: CallOverrides): Promise<BigNumber>;

    removeAdmin(
      oldAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setCloseFeeRate(
      newCFBP: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLicenseFeeCap(
      newLFCap: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLicenseFeeRate(
      newLFBP: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLicenseFeeRecipient(
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLyraRewardRecipient(
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    synthetixAdapter(overrides?: CallOverrides): Promise<BigNumber>;

    tradeOneClick(
      oneClickName: PromiseOrValue<string>,
      underlier: PromiseOrValue<string>,
      estimatedCost: PromiseOrValue<BigNumberish>,
      inputLegs: OneClicks.LegDetailsStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    tradingRewards(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    underlierToMarket(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addMarket(
      underlier: PromiseOrValue<string>,
      market: PromiseOrValue<string>,
      token: PromiseOrValue<string>,
      greekCache: PromiseOrValue<string>,
      pricer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addStrategy(
      oneClickName: PromiseOrValue<string>,
      legsIsCall: PromiseOrValue<boolean>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    closeAllPositions(
      underliers: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    closeAllPositionsByUnderlier(
      underlier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    closeFeeBasisPoint(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    closeSelectedPositions(
      toClose: OneClicks.PositionsToCloseStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    closeSelectedPositionsByUnderlier(
      underlier: PromiseOrValue<string>,
      positionIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deleteMarket(
      underlier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deleteStrategy(
      oneClickName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    emergencyWithdrawal(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getDeltas(
      underlier: PromiseOrValue<string>,
      strikeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getExistingPosition(
      underlier: PromiseOrValue<string>,
      strikeId: PromiseOrValue<BigNumberish>,
      isCall: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMinCollateralForStrike(
      underlier: PromiseOrValue<string>,
      isCall: PromiseOrValue<boolean>,
      isLong: PromiseOrValue<boolean>,
      strikeId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOptionPrices(
      underlier: PromiseOrValue<string>,
      strikeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStrikeIV(
      underlier: PromiseOrValue<string>,
      strikeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isAdmin(
      _Admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    licenseFeeBasisPoint(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    licenseFeeCap(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    licenseFeeRecipient(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lyraRewardRecipient(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    marketToToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    quoteAsset(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeAdmin(
      oldAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setCloseFeeRate(
      newCFBP: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLicenseFeeCap(
      newLFCap: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLicenseFeeRate(
      newLFBP: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLicenseFeeRecipient(
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLyraRewardRecipient(
      recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    synthetixAdapter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tradeOneClick(
      oneClickName: PromiseOrValue<string>,
      underlier: PromiseOrValue<string>,
      estimatedCost: PromiseOrValue<BigNumberish>,
      inputLegs: OneClicks.LegDetailsStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    tradingRewards(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    underlierToMarket(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
